### ISSUE TITLE
Unable to launch server: Multiple entries with same key: block.minecraft.nether_wart_block=Crimson Wart Block and block.minecraft.nether_wart_block=Nether Wart Block

### ISSUE THREAD

**Issue by ynerant** [MSandro/sky_fabrication2#13]
Hi,

I tried to launch a clean server with the modpack Sky Fabrication 2. I downloaded the latest server archive (1.0.1), which is available here: https://www.curseforge.com/minecraft/modpacks/sky-fabrication-2/files/3592220

I downloaded the file, unzipped it, downloaded the official Minecraft server as requested in the instructions, then I launched the server. The stacktrace is below:

```
[...]
[18:49:32] [main/INFO]: Plugin config reloaded
[18:49:32] [main/ERROR]: No data fixer registered for appliedenergistics2:singularity
[18:49:32] [main/ERROR]: No data fixer registered for appliedenergistics2:charged_quartz
[18:49:32] [main/ERROR]: No data fixer registered for appliedenergistics2:tiny_tnt_primed
[18:49:32] [main/ERROR]: No data fixer registered for appliedenergistics2:growing_crystal
Starting Mo Glass...
[18:49:41] [main/INFO]: Loading Xaero's Minimap - Stage 1/2 (Server)
[18:49:41] [main/INFO]: Loading Xaero's World Map - Stage 1/2 (Server)
[18:49:43] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:49:43] [main/INFO]: [bclib] Creating a new World, no fixes needed
[18:49:43] [main/INFO]: [DataFixerAPI] Applying Patch{betternether:5.3.5:21020677}
[18:49:43] [main/INFO]: [DataFixerAPI] Applying Patch{bclib:0.4.0:65536}
[18:49:43] [main/INFO]: [DataFixerAPI] Updating Patch-Level for 'betternether' from 0.0.0 to 5.3.5
[18:49:43] [main/INFO]: [DataFixerAPI] Updating Patch-Level for 'bclib' from 0.0.0 to 0.4.0
[18:49:43] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[18:49:43] [main/INFO]: Found new data pack dispenser_configurator/default_dispenser_configurators, loading it automatically
[18:49:44] [main/INFO]: Registered/Reloaded all your commands :P, you can now single command nuke!
Adding serverside commands..
[18:49:44] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2588.method_11025(class_2588.java:42)
	at net.minecraft.class_2588.method_27659(class_2588.java:143)
	at net.minecraft.class_2561.method_27657(class_2561.java:96)
	at net.minecraft.class_5348.getString(class_5348.java:91)
	at net.minecraft.class_2561.getString(class_2561.java:39)
	at com.mojang.brigadier.exceptions.CommandSyntaxException.<init>(CommandSyntaxException.java:27)
	at com.mojang.brigadier.exceptions.SimpleCommandExceptionType.createWithContext(SimpleCommandExceptionType.java:21)
	at com.mojang.brigadier.StringReader.readDouble(StringReader.java:142)
	at net.minecraft.class_2278.method_9743(class_2278.java:41)
	at net.minecraft.class_2280.method_9750(class_2280.java:87)
	at net.minecraft.class_2277.method_9738(class_2277.java:54)
	at net.minecraft.class_2277.parse(class_2277.java:21)
	at com.mojang.brigadier.tree.ArgumentCommandNode.isValidInput(ArgumentCommandNode.java:91)
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:102)
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:113)
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:113)
	at com.mojang.brigadier.CommandDispatcher.findAmbiguities(CommandDispatcher.java:695)
	at net.minecraft.class_2170.<init>(class_2170.java:235)
	at net.minecraft.class_5350.<init>(class_5350.java:39)
	at net.minecraft.class_5350.method_29466(class_5350.java:88)
	at net.minecraft.server.Main.main(Main.java:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	... 7 more
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: block.minecraft.nether_wart_block=Crimson Wart Block and block.minecraft.nether_wart_block=Nether Wart Block
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359)
	at net.minecraft.class_2477.method_29429(class_2477.java:45)
	at net.minecraft.class_2477.<clinit>(class_2477.java:33)
	... 33 more
```

I didn't find what mod causes this crash. I don't think that it is related to my configuration but if necessary I am running Debian Bullseye with Java 17. I also tried with Arch Linux and Java 17.

**Comment by ynerant** [comment]
Launching the modpack in the version 1.0-pre2 is working, so the issue seems to be between these two versions.

Client is however launching well.

**Comment by MSandro** [comment]
https://www.mediafire.com/file/so10cuksoxm2fa1/1.0.1.zip/file

Hello, please try this file, I know about this issue.

**Comment by ynerant** [comment]
It seems to work now, thank you. Do you know what was the issue?

**Comment by MSandro** [comment]
as I know it was an broken version of Computer Craft (CC: Restitched) which is working on Client but not on servers.
I've included an patched version in my first Server File, but this was maybe changed from Curseforge to the original Mod version.
Don't know exactly.
